In [1]:
# Dependencies
import pandas as pd

In [2]:
# Converting clean Netflix csv to df
netflix_df = pd.read_csv("OutputData/NetflixDB.csv")
netflix_df

,IMDB_id,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Country,IMDB_rating,RT_rating,Metacritic_rating,Type,Duplicate,Duplicate1
0,tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,15%,41/100,movie,False,False
1,tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,NaN,53/100,movie,False,False
2,tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",NaN,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,NaN,NaN,series,False,False
3,tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",NaN,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,NaN,NaN,series,False,False
4,tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",NaN,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,NaN,NaN,series,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,tt4257950,Russell Madness,2015,PG,10 May 2015,92 min,Family,Robert Vince,"Aaron Brooks, Kirsten Hansen, Anna McRoberts","Sean Giambrone, David Milchard, Steve Richmond",English,United States,4.2,NaN,NaN,movie,False,False
440,tt3462880,Wiener Dog Internationals,2017,G,03 Mar 2017,92 min,Family,Kevan Peterson,Kevan Peterson,"Morgan Fairchild, Jason London, Bryan Batt",NaN,United States,4.4,NaN,NaN,movie,False,False
441,tt5449296,Pup Star,2016,G,30 Aug 2016,92 min,"Comedy, Family",Robert Vince,"Kirsten Hansen (screenplay), Anna McRoberts (s...","Carla Jimenez, Makenzie Moss, Susie Wall, Jona...",English,Canada,4.4,NaN,NaN,movie,False,False
442,tt6500946,Precious Puppies,2003,NaN,NaN,53 min,Documentary,Greg Grainger,NaN,Lizzy Lovette,English,Australia,6.1,NaN,NaN,movie,False,False
443,tt6780296,Beary Tales,2013,NaN,NaN,51 min,Documentary,"Hira Klatt, Marcella Muller, Angelika Sigl",NaN,Volker Arzt,English,United States,8.0,NaN,NaN,movie,False,False

In [3]:
# Converting clean Crackle csv to df
crackle_df = pd.read_csv("OutputData/crackle.csv")
crackle_df

,IMDB_id,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Country,IMDB_rating,RT_rating,Metacritic_rating,Type
0,tt0115082,3rd Rock from the Sun,1996–2001,TV-PG,09 Jan 1996,60 min,"Comedy, Family, Sci-Fi",NaN,"Bonnie Turner, Terry Turner","John Lithgow, Jane Curtin, Kristen Johnston",English,United States,7.7,None,None,series
1,tt0313202,An Angel for May,2002,TV-G,23 Dec 2002,95 min,"Drama, Family, Fantasy",Harley Cokeliss,"Melvin Burgess (based on the novel by), Peter ...","Tom Wilkinson, Charlotte Wakefield, Matthew Be...",English,United Kingdom,7.0,None,None,movie
2,tt0264366,And Never Let Her Go,2001,NaN,01 Apr 2001,200 min,"Crime, Drama, Mystery",Peter Levin,"Adam Greenman (teleplay), Ann Rule (book)","Mark Harmon, Rachel Ward, Kathryn Morris, Stev...",English,United States,6.4,None,None,movie
3,tt0200323,Animal Tales,1997–,NaN,NaN,NaN,NaN,NaN,NaN,"Jennifer Badger, Brian Palermo",English,United States,NaN,None,None,series
4,tt0402619,Awesome Adventures,1998–2015,NaN,NaN,30 min,Documentary,NaN,NaN,"Mystro Clark, Anthony Montgomery",English,United States,6.6,None,None,series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,tt0419373,Supernova,2005,Not Rated,05 Sep 2005,172 min,"Action, Adventure, Drama, Sci-Fi, Thriller",John Harrison,"Steven H. Berman, Don Keith Opper","Luke Perry, Tia Carrere, Peter Fonda, Clemency...","English, French","United States, South Africa",3.7,None,None,movie
223,tt0137311,The Karate Kid,1989,TV-Y7-FV,09 Sep 1989,NaN,"Animation, Short, Action",NaN,NaN,"Joey Dedio, Robert Ito, Janice Kawaye",English,United States,4.9,None,None,series
224,tt0163953,The Net,1998–1999,NaN,19 Jul 1998,45 min,Thriller,NaN,"Rob Cowan, Deborah Pratt, Irwin Winkler","Brooke Langton, Joseph Bottoms, Eric Szmanda",English,"United States, Canada",6.2,None,None,series
225,tt0169501,Ultraviolet,1998,NaN,31 Jul 2000,300 min,"Horror, Sci-Fi, Thriller",NaN,NaN,"Jack Davenport, Susannah Harker, Idris Elba",English,United Kingdom,7.9,None,None,series
226,tt0215446,A Twist in the Tale,1999,TV-PG,06 Feb 1999,52 min,"Drama, Family, Mystery",NaN,Raymond Thompson,"William Shatner, Robin Johnson, Chelsie Presto...",English,"United States, New Zealand",7.3,None,None,series

In [4]:
# Converting clean DisneyPlus csv to df
disneyplus_df = pd.read_csv("OutputData/disneyplus.csv")
disneyplus_df

,IMDB_id,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Country,IMDB_rating,RT_rating,Metacritic_rating,Type
0,tt0147800,10 Things I Hate About You,1999,PG-13,31 Mar 1999,97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith, William Shakesp...","Heath Ledger, Julia Stiles, Joseph Gordon-Levitt","English, French",United States,7.3,69%,70/100,movie
1,tt7019028,101 Dalmatian Street,2018–2020,TV-Y7,25 Mar 2019,22 min,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis",English,"United Kingdom, United States, Canada",6.3,NaN,NaN,series
2,tt0115433,101 Dalmatians,1996,G,27 Nov 1996,103 min,"Adventure, Comedy, Crime",Stephen Herek,"Dodie Smith, John Hughes","Glenn Close, Jeff Daniels, Joely Richardson","English, Spanish","United States, United Kingdom",5.7,41%,49/100,movie
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,2002,G,21 Jan 2003,74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,United States,5.8,67%,NaN,movie
4,tt0211181,102 Dalmatians,2000,G,22 Nov 2000,100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith, Kristen Buckley, Brian Regan","Glenn Close, Gérard Depardieu, Ioan Gruffudd",English,"United States, United Kingdom, France",4.9,31%,35/100,movie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
889,tt3544734,Zapped,2014,TV-G,23 Jun 2014,102 min,"Comedy, Family, Fantasy",Peter DeLuise,"Leslie Margolis (based on the novel ""Boys Are ...","Zendaya, Chanelle Peloso, Spencer Boldman, Emi...",English,"Canada, USA",5.1,NaN,NaN,movie
890,tt0186726,Zenon: Girl of the 21st Century,1999,TV-G,23 Jan 1999,97 min,"Adventure, Comedy, Family, Sci-Fi",Kenneth Johnson,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Raven-Symoné, Stuart Pankin, H...",English,United States,6.4,NaN,NaN,movie
891,tt0271271,Zenon: The Zequel,2001,TV-G,12 Jan 2001,100 min,"Comedy, Family, Adventure, Sci-Fi",Manny Coto,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Shadia Simmons, Lauren Maltby,...",English,"USA, New Zealand",5.9,NaN,NaN,movie
892,tt0379060,Zenon: Z3,2004,TV-G,11 Jun 2004,81 min,"Adventure, Comedy, Family, Sci-Fi",Steve Rash,"Marilyn Sadler (character from the book ""Zenon...","Kirsten Storms, Lauren Maltby, Alyson Morgan, ...",English,United States,5.5,NaN,NaN,movie
893,tt2948356,Zootopia,2016,PG,04 Mar 2016,108 min,"Animation, Adventure, Comedy","Byron Howard, Rich Moore, Jared Bush","Byron Howard, Rich Moore, Jared Bush","Ginnifer Goodwin, Jason Bateman, Idris Elba",English,United States,8.0,98%,78/100,movie

In [5]:
# Concat different csvs into single movies database and remove duplicates
frames = [netflix_df, crackle_df, disneyplus_df]
movies_db = pd.concat(frames).drop_duplicates(subset=["IMDB_id"], ignore_index=True)

In [6]:
movies_db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1517 entries, 0 to 1516
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IMDB_id            1517 non-null   object
 1   Title              1517 non-null   object
 2   Year               1517 non-null   object
 3   Rated              1278 non-null   object
 4   Released           1486 non-null   object
 5   Runtime            1438 non-null   object
 6   Genre              1508 non-null   object
 7   Director           916 non-null    object
 8   Writer             1242 non-null   object
 9   Actors             1493 non-null   object
 10  Language           1487 non-null   object
 11  Country            1492 non-null   object
 12  IMDB_rating        1481 non-null   float64
 13  RT_rating          682 non-null    object
 14  Metacritic_rating  615 non-null    object
 15  Type               1517 non-null   object
 16  Duplicate          444 non-null    object
 17  Duplicate1         444 non-null    object
dtypes: float64(1), object(17)
memory usage: 213.5+ KB

In [7]:
# Delete columns
del movies_db["RT_rating"]
del movies_db["Metacritic_rating"]
del movies_db["Duplicate"]
del movies_db["Duplicate1"]

In [8]:
movies_db.rename(columns = {'IMDB_id':'imdb_id','Title':'title','Year':'year','Rated':'rated',
                            'Released':'released','Runtime':'runtime', 'Genre':'genre','Director':'director',
                             'Writer':'writer','Actors':'actors','Language':'language','Country':'country',
                            'IMDB_rating':'imdb_rating','Type': 'type'},inplace = True)

In [9]:
# Display final movies database
movies_db

,imdb_id,title,year,rated,released,runtime,genre,director,writer,actors,language,country,imdb_rating,type
0,tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,movie
1,tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,movie
2,tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",NaN,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,series
3,tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",NaN,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,series
4,tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",NaN,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,series
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1512,tt6878820,Z-O-M-B-I-E-S,2018,TV-G,16 Feb 2018,94 min,"Family, Musical, Romance",Paul Hoen,"David Light, Joseph Raso, David Light (based o...","Milo Manheim, Meg Donnelly, Trevor Tordjman, K...",English,United States,6.3,movie
1513,tt3544734,Zapped,2014,TV-G,23 Jun 2014,102 min,"Comedy, Family, Fantasy",Peter DeLuise,"Leslie Margolis (based on the novel ""Boys Are ...","Zendaya, Chanelle Peloso, Spencer Boldman, Emi...",English,"Canada, USA",5.1,movie
1514,tt0186726,Zenon: Girl of the 21st Century,1999,TV-G,23 Jan 1999,97 min,"Adventure, Comedy, Family, Sci-Fi",Kenneth Johnson,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Raven-Symoné, Stuart Pankin, H...",English,United States,6.4,movie
1515,tt0271271,Zenon: The Zequel,2001,TV-G,12 Jan 2001,100 min,"Comedy, Family, Adventure, Sci-Fi",Manny Coto,"Marilyn Sadler (book), Roger Bollen (book), St...","Kirsten Storms, Shadia Simmons, Lauren Maltby,...",English,"USA, New Zealand",5.9,movie
1516,tt0379060,Zenon: Z3,2004,TV-G,11 Jun 2004,81 min,"Adventure, Comedy, Family, Sci-Fi",Steve Rash,"Marilyn Sadler (character from the book ""Zenon...","Kirsten Storms, Lauren Maltby, Alyson Morgan, ...",English,United States,5.5,movie

In [10]:
# Convert movies dataframe to movies csv
movies_db.to_csv("OutputData/movies.csv", index=False)

In [11]:
# Create new platform dataframe
platform_db = pd.DataFrame({"platform_id": ["P01", "P02", "P03"], 
                            "platform_name": ["Netflix", "Disney Plus", "Crackle"]})
platform_db

  platform_id platform_name
0         P01       Netflix
1         P02   Disney Plus
2         P03       Crackle

In [12]:
# Convert platform dataframe to platform csv
platform_db.to_csv("OutputData/platform.csv", index=False)

Validating the dataframes (duplicates etc.)

In [14]:
movies_db.loc[movies_db["title"] == "Aladdin"]

,imdb_id,title,year,rated,released,runtime,genre,director,writer,actors,language,country,imdb_rating,type
682,tt6139732,Aladdin,2019,PG,24 May 2019,128 min,"Action, Adventure, Family",Guy Ritchie,"John August, Guy Ritchie","Will Smith, Mena Massoud, Naomi Scott","English, Arabic","United Kingdom, United States, Australia",6.9,movie
683,tt0103639,Aladdin,1992,G,25 Nov 1992,90 min,"Animation, Adventure, Comedy","Ron Clements, John Musker","Ron Clements, John Musker, Ted Elliott","Scott Weinger, Robin Williams, Linda Larkin",English,United States,8.0,movie

In [15]:
xyz = netflix_df.copy()

In [16]:
xyz["status"] = xyz.duplicated(subset=["imdb_id"])
xyz

,IMDB_id,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Country,IMDB_rating,RT_rating,Metacritic_rating,Type,Duplicate,Duplicate1,status
0,tt0381707,White Chicks,2004,PG-13,23 Jun 2004,109 min,"Comedy, Crime",Keenen Ivory Wayans,"Keenen Ivory Wayans, Shawn Wayans, Marlon Wayans","Marlon Wayans, Shawn Wayans, Busy Philipps",English,United States,5.6,15%,41/100,movie,False,False,False
1,tt0425210,Lucky Number Slevin,2006,R,07 Apr 2006,110 min,"Crime, Drama, Thriller",Paul McGuigan,Jason Smilovic,"Josh Hartnett, Ben Kingsley, Morgan Freeman",English,"United States, Germany, United Kingdom, Canada",7.7,NaN,53/100,movie,False,False,False
2,tt0413573,Grey's Anatomy,2005–,TV-14,27 Mar 2005,41 min,"Drama, Romance",NaN,Shonda Rhimes,"Ellen Pompeo, Chandra Wilson, James Pickens Jr.",English,United States,7.5,NaN,NaN,series,False,False,False
3,tt0455275,Prison Break,2005–2017,TV-14,29 Aug 2005,44 min,"Action, Crime, Drama",NaN,Paul T. Scheuring,"Dominic Purcell, Wentworth Miller, Amaury Nolasco","English, Arabic, Spanish","United Kingdom, United States",8.3,NaN,NaN,series,False,False,False
4,tt0460649,How I Met Your Mother,2005–2014,TV-14,19 Sep 2005,22 min,"Comedy, Romance",NaN,"Carter Bays, Craig Thomas","Josh Radnor, Jason Segel, Cobie Smulders","English, Persian, Chinese",United States,8.3,NaN,NaN,series,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,tt4257950,Russell Madness,2015,PG,10 May 2015,92 min,Family,Robert Vince,"Aaron Brooks, Kirsten Hansen, Anna McRoberts","Sean Giambrone, David Milchard, Steve Richmond",English,United States,4.2,NaN,NaN,movie,False,False,False
440,tt3462880,Wiener Dog Internationals,2017,G,03 Mar 2017,92 min,Family,Kevan Peterson,Kevan Peterson,"Morgan Fairchild, Jason London, Bryan Batt",NaN,United States,4.4,NaN,NaN,movie,False,False,False
441,tt5449296,Pup Star,2016,G,30 Aug 2016,92 min,"Comedy, Family",Robert Vince,"Kirsten Hansen (screenplay), Anna McRoberts (s...","Carla Jimenez, Makenzie Moss, Susie Wall, Jona...",English,Canada,4.4,NaN,NaN,movie,False,False,False
442,tt6500946,Precious Puppies,2003,NaN,NaN,53 min,Documentary,Greg Grainger,NaN,Lizzy Lovette,English,Australia,6.1,NaN,NaN,movie,False,False,False
443,tt6780296,Beary Tales,2013,NaN,NaN,51 min,Documentary,"Hira Klatt, Marcella Muller, Angelika Sigl",NaN,Volker Arzt,English,United States,8.0,NaN,NaN,movie,False,False,False

In [17]:
xyz.loc[xyz["status"] == True]

Empty DataFrame
Columns: [IMDB_id, Title, Year, Rated, Released, Runtime, Genre, Director, Writer, Actors, Language, Country, IMDB_rating, RT_rating, Metacritic_rating, Type, Duplicate, Duplicate1, status]
Index: []